name: TypeCheck

on:
  push:
    branches:
      - "**"
    pull_request:
      branches:
        - "**"

job:
  type_check:
    runs_on: ubuntu_latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.0x"

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check
